spring.application.name=sprintboot-websocket-eclipse
server.port=8087
server.servlet.session.timeout=12h
logging.file.name=logs/connector-rr.log
logging.level.it.icron.icronium.connector.rr.integration.RRGaraDettaglioService=INFO
logging.level.it.icron.icronium.connector.rr.integration.PostUploader=INFO
